# default Profile
spring:
  profiles:
    active: "build"
---
# build config
spring:
  config:
    activate:
      on-profile: "build"
  datasource:
    url: "jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul"
    username: test
    password: Asdf1234!!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: true
  data:
    redis:
      host: localhost
      port: 6379
---
# local config
spring:
  config:
    activate:
      on-profile: "local"
  datasource:
    url: "jdbc:mysql://db:3306/test?serverTimezone=Asia/Seoul"
    username: test
    password: Asdf1234!!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: true
  data:
    redis:
      host: localhost
      port: 6380
---
# test config
spring:
  config:
    activate:
      on-profile: "test"
  datasource:
    url: "jdbc:mysql://localhost:3308/test?serverTimezone=Asia/Seoul"
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: true
  data:
    redis:
      host: localhost
      port: 6381
---
